version: '3.8'

services:
  ticketing-netsuite-server:
    build: .
    container_name: ticketing-netsuite-server
    restart: unless-stopped
    ports:
      - "7002:7002"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1  
      DB_PORT: 3306
      DB_DATABASE: ticketing_netsuite
      DB_USERNAME: root
      DB_PASSWORD: D@pho04051983 
